# -*- coding: utf-8 -*-
"""
@author: Asma Baccouche
"""

def get_tags(path):
    
    Eng_TAGS=['RBS','RBR','RB','JJS','JJR','JJ','MD','VVN','VBP','VVZ','VVD','VBG','VV',
          'VVP','IN','VVG','VBZ','VB','VBN','VBD','NN','NP','NNS','NNP','NNPS','DT','W','WDT','WP','WP$','WRB','CC','CD','UH','EX','FW',
          'LS','PDT','POS','PRP','PRP$','SYM','TO']
    
    Fr_TAGS=['ADV','ADJ','VER:ppre','VER:pres','VER:simp','VER:subi','VER:subp','VER:infi',
    'VER:pper','VER:cond','VER:futu','VER:impe','VER:impf','NOM','NAM','PRO','PRO:DEM','PRO:IND','PRO:PER','PRO:POS'
    'PRO:REL','PRP','DET:POS','INT','KON','DET:ART','NUM','ABR','RP:det','PUN','PUN:cit','SENT','SYM']
    
    Ar_TAGS=['ADV','ADJ','VERB_IMPERFECT','IVSUFF_DO:3MS','IVSUFF_DO:2FS','PVSUFF_SUBJ:3MD','PVSUFF_DO:2MP',
             'PVSUFF_SUBJ:3FS','PVSUFF_SUBJ:3MP','PVSUFF_DO:1P','PVSUFF_DO:3FP','PVSUFF_DO:2MS','PVSUFF_DO:1S',
             'PVSUFF_DO:2FP','PVSUFF_DO:2D','CVSUFF_DO:1P','PVSUFF_SUBJ:2FS','PVSUFF_DO:3FS','REL_PRON',
             'PVSUFF_DO:3MP','PVSUFF_SUBJ:3FD','PVSUFF_DO:3MS','PVSUFF_SUBJ:1S','PVSUFF_SUBJ:1P','PVSUFF_DO:2FS',
             'PVSUFF_SUBJ:2MS','IVSUFF_SUBJ:D_MOOD:I','PVSUFF_SUBJ:3FP','PVSUFF_SUBJ:2MP',
             'PVSUFF_SUBJ:2FP','IVSUFF_DO:2D','IVSUFF_DO:2MS','IVSUFF_SUBJ:MP_MOOD:I','IVSUFF_SUBJ:D_MOOD:SJ',
             'PVSUFF_SUBJ:3MS','IVSUFF_SUBJ:2FS_MOOD:SJ','IVSUFF_DO:3FS','IVSUFF_DO:2MP','IVSUFF_DO:3D','IVSUFF_DO:3MP',
             'IVSUFF_SUBJ:MP_MOOD:SJ','IVSUFF_DO:1P','IVSUFF_DO:2FP','IVSUFF_SUBJ:FP','IVSUFF_DO:1S','NOUN','NOUN_PROP',
             'IVSUFF_SUBJ:2FS_MOOD:I','CVSUFF_DO:3MP','CVSUFF_SUBJ:2MP','CVSUFF_SUBJ:2MS','CVSUFF_DO:1P',
             'CVSUFF_SUBJ:2FS','CVSUFF_DO:3MP','CVSUFF_DO:3FS','CVSUFF_DO:1S','POSS_PRON_2MS','POSS_PRON_2FS',
             'POSS_PRON_3FS','DEM_PRON_MS','NSUFF_MASC_DU_NOM_POSS','NSUFF_MASC_DU_NOM_POSS'
             'INTERROG_PART','NSUFF_MASC_PL_ACCGEN','NSUFF_FEM_DU_ACCGEN','NSUFF_MASC_DU_ACCGEN_POSS','NEG_PART',
             'NSUFF_FEM_SG','NSUFF_MASC_SG_ACC_INDEF','INTERJ','POSS_PRON_2MP','PRON_3MS','POSS_PRON_3D',
             'NSUFF_FEM_DU_NOM_POSS','POSS_PRON_3MS','PRON_2MS','FUT_PART','NSUFF_FEM_PL','ABBREV',
             'NSUFF_MASC_DU_NOM','PRON_3D','PRON_1S','PRON_3FP','PRON_3FS','POSS_PRON_1S','PRON_1P','PRON_2FS'
             'DEM_PRON_MP','DEM_PRON_FP','CONJ','DEM_PRON_FS','NSUFF_MASC_PL_NOM_POSS','NSUFF_FEM_DU_ACCGEN_POSS',
             'NSUFF_FEM_DU_NOM','PRON_2MP','PREP','POSS_PRON_1P','NSUFF_MASC_DU_ACCGEN','POSS_PRON_3MP',
             'DET','POSS_PRON_2FP','NSUFF_MASC_PL_NOM','PRON_2FP','FUNC_WORD','DEM_PRON_F','PRON_3MP','NUMERIC_COMMA']    
    
    if path == 'English' :
        return(Eng_TAGS)
    else :
        if path == 'French' :
            return(Fr_TAGS)
        else :
            return(Ar_TAGS)
          